"""empty message

Revision ID: 5d1b52f77fad
Revises: 
Create Date: 2021-03-28 20:47:27.445866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1b52f77fad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreCompleto', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasenia', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('comuna', sa.String(length=100), nullable=False),
    sa.Column('tipoVivienda', sa.String(length=20), nullable=False),
    sa.Column('numDepto', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('f_creacion', sa.Date(), nullable=True),
    sa.Column('f_modificacion', sa.Date(), nullable=True),
    sa.Column('f_eliminacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('nombreAutor', sa.String(length=100), nullable=False),
    sa.Column('editorial', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=100), nullable=False),
    sa.Column('asignatura', sa.String(length=100), nullable=False),
    sa.Column('estadoNuevoUsado', sa.String(length=100), nullable=False),
    sa.Column('condicionOriginalCopia', sa.String(length=100), nullable=False),
    sa.Column('tipoIntercambio', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('comentarios', sa.String(length=100), nullable=False),
    sa.Column('f_creacion', sa.Date(), nullable=True),
    sa.Column('f_modificacion', sa.Date(), nullable=True),
    sa.Column('f_eliminacion', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros')
    op.drop_table('clientes')
    # ### end Alembic commands ###
